#!/usr/bin/env node

/**
 * This file makes sure the above shebang is the very first LOC
 * It should NOT be included in any compilation stages!
 *
 * It is required to make the system execute this code with Node
 *
 * Read more: https://stackoverflow.com/a/33510581/2367649
 */

require('reflect-metadata');
require('./tsconfig-paths-bootstrap.js');
require('./main.js');
